### ISSUE TITLE
关于注册

### ISSUE THREAD

**Issue by ZENG61** [Biubush/alys#1]
能否不需要邮件服务器，太麻烦了

**Comment by Biubush** [comment]
可以考虑内置一个公用smtp账户，下个更新会加上。

**Comment by Biubush** [comment]
> 能否不需要邮件服务器，太麻烦了

已更新

**Comment by bao3** [comment]
这个 issue 还是 open 的，我想汇报的是，设置邮件服务器那里，没办法指定 smtp 服务器，发不了邮件，有没有办法可以解决一下
